// src/ai-router/covered-intents.js

// Intent GIÀ coperti dalla guida di Via Arenula
export const COVERED_INTENTS = new Set([
  "wifi",
  "wifi_troubleshooting",
  "trash",
  "heating",
  "AC",
  "electric_panel",
  "water",
  "bathroom",
  "linens_towels",
  "kitchen",
  "check_in",
  "early_checkin",
  "check_out",
  "late_checkout",
  "building",
  "transport",
  "luggage_storage",
  "eat",
  "drink",
  "visit",
  "experiences",
  "day_trips",
  "tickets",
  "museums",
  "exhibitions",
  "city_tax_info",
  "city_tax_payment_issue",
  "payment_methods",
  "id_documents",
  "receipt_rental",
  "receipt_city_tax",
  "house_rules",
  "laundry",
  "emergency",
  "services"
]);
