export const ANSWERS = {
  arenula: {
    it: {
      wifi: "Wi-Fi: Il router è sulla scrivania vicino alla finestra. Giralo per leggere SSID e password sull'etichetta. Se non funziona: controlla che sia acceso, scollegalo 30 secondi e ricollegalo. Se il problema continua, scrivimi.",
      trash: "Spazzatura: Trovi le buste in cucina. Chiudi bene i sacchetti e portali nei cassonetti nella corte prima dell'uscita. Facciamo raccolta differenziata: segui le indicazioni e non lasciare immondizia nel vano scala o fuori dalla porta.Una volta che hai diviso tutta l'immondizia, prima del check-out portala giù nella corte esterna. Prima dell'uscita, sul lato destro, ci sono i vari secchioni. Disponi l'immondizia per tipologie in ogni secchione. Grazie.",
      heating: "Riscaldamento: Usa il telecomando dell'aria condizionata. Premi MODE finché appare il simbolo del sole, imposta 26 °C e potenza 1. Spegni sempre il condizionatore quando esci.",
      electric_panel: "Quadro elettrico: Andando verso il bagno, sulla destra prima della porta trovi il quadro. Se manca la corrente: 1) alza gli interruttori abbassati; 2) se sono già tutti su, togli il pannello sopra, rialza l'interruttore generale e spegni qualche elettrodomestico.",
      check_in: "Check-in dalle 15:00. Citofono C8. Portone attivo 08:00–13:00 e 15:30–18:00. Portineria: Paolo. Per aiuto: +39 335 5245756.",
      check_out: "Check-out: Prima di partire spegni luci e A/C, chiudi le finestre, lascia le chiavi sul tavolo e chiudi la porta delicatamente.",
      city_tax_info: "Tassa di soggiorno: A Roma è obbligatoria per gli ospiti non residenti. Per questo appartamento è di 5 € a persona per notte, fino a un massimo di 10 notti. La incassiamo per conto del Comune di Roma.",
      laundry: "Lavanderia: Se devi lavare vestiti o asciugamani, scrivimi e ti indico la soluzione migliore in zona in base ai tuoi orari.",
      building: "Edificio: Citofono C8. Ascensore riservato ai proprietari (non utilizzarlo). Portone 08:00–13:00 e 15:30–18:00. Portineria: Paolo.",
      emergency: "Emergenze: UE 112 • Polizia 113 • Ambulanza 118 • Vigili del Fuoco 115 • Medico (EN) +39 06 488 2371 • Veterinario 24h +39 06 660 681",
      air_conditioning: "Aria condizionata: Usa il telecomando. Premi MODE finché appare il simbolo del fiocco di neve, imposta 24 °C e potenza auto. Spegni sempre quando esci.",
      parking: "Parcheggio: L'appartamento si trova nel centro storico (ZTL). L'accesso in auto è consentito solo dal lunedì al sabato dalle 19:00 alle 7:30. Per trovare il parcheggio più vicino cerca su Google Maps l'indirizzo dell'appartamento. Se hai difficoltà, chiamami: +39 335 5245756.",
      services: "Per informazioni su farmacie, ospedali, bancomat e altri servizi consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      transport: "Per informazioni su trasporti, metro, bus e aeroporti consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      restaurants: "Per consigli su ristoranti, pizzerie e locali consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      shopping: "Per informazioni su negozi e mercati consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      attractions: "Per scoprire cosa visitare a Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      day_trips: "Per informazioni su gite ed escursioni fuori Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      tickets: "Per informazioni su biglietti per musei, eventi e partite consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=it",
      gas_leak: "Se sentite odore di gas, controllate subito la macchina del gas e verificate che tutte le manopole nere, cioè quelle poste sul lato destro della macchina del gas, siano ben chiuse e nella posizione corretta. Subito dopo, di fronte alla macchina del gas, leggermente sul lato destro, troverete una manopola metallica: ruotatela verso il basso per chiudere completamente il circuito del gas. Dopo aver effettuato queste operazioni, chiamatemi immediatamente, perché è necessario che io controlli l’appartamento.",
water_leak: "Nel caso si verifichi una perdita d’acqua nell’appartamento, la prima cosa da fare è andare in bagno. Guardando lo specchio, sul lato sinistro, leggermente nell’angolo del muro, troverete un cappuccio di metallo: svitatelo. Dietro il cappuccio c’è un rubinetto nero: chiudetelo completamente, perché è la valvola di chiusura dell’acqua dell’intero appartamento. Una volta chiusa l’acqua, chiamate il portiere e subito dopo avvertitemi.",
lost_keys: "Nel caso in cui doveste perdere le chiavi, la prima cosa da fare è chiamarmi immediatamente e avvertirmi, così da poter gestire la situazione nel modo corretto."
    },
    en: {
      wifi: "Wi-Fi: The router is on the desk near the window. Turn it to read the SSID and password on the label. If it doesn't work: check it's on, unplug it for 30 seconds and plug it back in. If the issue continues, message me.",
      trash: "Trash: Bags are in the kitchen. Close them well and take them to the bins in the courtyard before leaving. We do recycling: follow the signs and do not leave trash in the stairwell or outside the apartment door.Once you have separated all the waste, before check-out please take it down to the outdoor courtyard. Before the exit, on the right-hand side, you will find the bins. Place each type of waste in the appropriate bin. Thank you.",
      heating: "Heating: Use the A/C remote control. Press MODE until the SUN symbol appears, set 26 °C and power level 1. Always turn it off when leaving.",
      electric_panel: "Electric panel: Walking toward the bathroom, on the right before the door. If there's no power: 1) switch any lowered breakers back up; 2) if all are up, remove the upper panel, reset the main switch and turn off some appliances.",
      check_in: "Check-in from 3:00 PM. Intercom C8. Building door active 8:00–13:00 and 15:30–18:00. Doorman: Paolo. Help: +39 335 5245756.",
      check_out: "Check-out: Before leaving, turn off lights and A/C, close the windows, leave the keys on the table and close the door gently.",
      city_tax_info: "City tax: Mandatory in Rome for non-residents. For this apartment it is €5 per person per night, up to a maximum of 10 nights. Collected on behalf of the City of Rome.",
      laundry: "Laundry: If you need to wash clothes or towels, message me and I'll suggest the best option nearby based on your schedule.",
      building: "Building: Intercom C8. Elevator is reserved for owners (please do not use it). Main door 8:00–13:00 and 15:30–18:00. Doorman: Paolo.",
      emergency: "Emergencies: EU 112 • Police 113 • Ambulance 118 • Fire Brigade 115 • Doctor (EN) +39 06 488 2371 • 24h Vet +39 06 660 681",
      air_conditioning: "Air conditioning: Use the remote control. Press MODE until the snowflake symbol appears, set 24 °C and auto power. Always turn it off when leaving.",
      parking: "Parking: The apartment is in the historic center (ZTL - Limited Traffic Zone). Car access is allowed only Monday to Saturday from 7:00 PM to 7:30 AM. To find the nearest parking, search the apartment address on Google Maps. If you need help, call me: +39 335 5245756.",
      services: "For information on pharmacies, hospitals, ATMs and other services, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      transport: "For information on transport, metro, buses and airports, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      restaurants: "For restaurant, pizzeria and bar recommendations, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      shopping: "For information on shops and markets, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      attractions: "To discover what to visit in Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      day_trips: "For information on day trips and excursions outside Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      tickets: "For information on tickets for museums, events and matches, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=en",
      gas_leak: "If you smell gas, immediately check the gas unit and make sure that all the black knobs on the right side are fully closed and in the correct position. Then, in front of the gas unit, slightly on the right side, you will find a metal valve: turn it downward to completely shut off the gas supply. After doing this, please call me immediately so I can check the apartment.",
water_leak: "In case of a water leak in the apartment, go to the bathroom. Looking at the mirror, on the left side near the corner of the wall, you will find a metal cap: unscrew it. Behind the cap there is a black valve: close it completely, as it is the main water shut-off for the entire apartment. Once the water is shut off, call the building concierge and then inform me immediately.",
lost_keys: "If you lose the keys, the first thing to do is call me immediately and inform me, so I can handle the situation properly."
    },
    fr: {
      wifi: "Wi-Fi : Le routeur est sur le bureau près de la fenêtre. Tournez-le pour lire le SSID et le mot de passe sur l'étiquette. S'il ne fonctionne pas : vérifiez qu'il est allumé, débranchez-le 30 secondes puis rebranchez-le. Sinon, écrivez-moi.",
      trash: "Déchets : Les sacs sont dans la cuisine. Fermez-les bien et jetez-les dans les bacs de la cour avant de partir. Tri sélectif obligatoire : suivez les indications et ne laissez rien dans l'escalier ou devant la porte.Une fois tous les déchets triés, avant le check-out, veuillez les descendre dans la cour extérieure. Avant la sortie, sur le côté droit, se trouvent les conteneurs. Déposez chaque type de déchet dans le conteneur correspondant. Merci.",
      heating: "Chauffage : Utilisez la télécommande de la climatisation. Appuyez sur MODE jusqu'au symbole soleil, réglez à 26 °C et puissance 1. Éteignez toujours en sortant.",
      electric_panel: "Tableau électrique : En allant vers la salle de bain, à droite avant la porte. En cas de coupure : 1) remontez les disjoncteurs baissés ; 2) s'ils sont tous levés, retirez le panneau supérieur, réarmez le général et éteignez quelques appareils.",
      check_in: "Arrivée à partir de 15h00. Interphone C8. Porte principale active 8h00–13h00 et 15h30–18h00. Concierge : Paolo. Aide : +39 335 5245756.",
      check_out: "Départ : Avant de partir, éteignez lumières et climatisation, fermez les fenêtres, laissez les clés sur la table et fermez la porte doucement.",
      city_tax_info: "Taxe de séjour : Obligatoire à Rome pour les non-résidents. Pour cet appartement : 5 € par personne et par nuit, maximum 10 nuits. Perçue pour la Ville de Rome.",
      laundry: "Blanchisserie : Si vous devez laver des vêtements ou serviettes, écrivez-moi et je vous indiquerai la meilleure solution à proximité.",
      building: "Immeuble : Interphone C8. Ascenseur réservé aux propriétaires (merci de ne pas l'utiliser). Porte 8h00–13h00 et 15h30–18h00. Concierge : Paolo.",
      emergency: "Urgences : UE 112 • Police 113 • Ambulance 118 • Pompiers 115 • Médecin (EN) +39 06 488 2371 • Vétérinaire 24h +39 06 660 681",
      air_conditioning: "Climatisation : Utilisez la télécommande. Appuyez sur MODE jusqu'au symbole flocon, réglez à 24 °C et puissance auto. Éteignez toujours en sortant.",
      parking: "Parking : L'appartement se trouve dans le centre historique (ZTL - Zone à Trafic Limité). L'accès en voiture est autorisé uniquement du lundi au samedi de 19h00 à 7h30. Pour trouver le parking le plus proche, recherchez l'adresse de l'appartement sur Google Maps. En cas de difficulté, appelez-moi : +39 335 5245756.",
      services: "Pour les informations sur pharmacies, hôpitaux, distributeurs et autres services, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      transport: "Pour les informations sur transports, métro, bus et aéroports, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      restaurants: "Pour les recommandations de restaurants, pizzerias et bars, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      shopping: "Pour les informations sur magasins et marchés, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      attractions: "Pour découvrir quoi visiter à Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      day_trips: "Pour les informations sur excursions d'une journée hors de Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      tickets: "Pour les informations sur billets pour musées, événements et matchs, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=fr",
      gas_leak: "Si vous sentez une odeur de gaz, vérifiez immédiatement l’appareil de gaz et assurez-vous que tous les boutons noirs situés sur le côté droit sont bien fermés. Ensuite, devant l’appareil, légèrement sur la droite, vous trouverez une vanne métallique : tournez-la vers le bas pour couper complètement le gaz. Après ces opérations, appelez-moi immédiatement afin que je puisse vérifier l’appartement.",
water_leak: "En cas de fuite d’eau dans l’appartement, allez dans la salle de bain. En regardant le miroir, sur le côté gauche près de l’angle du mur, vous trouverez un capuchon en métal : dévissez-le. Derrière se trouve un robinet noir : fermez-le complètement, car il s’agit de la vanne principale d’eau de l’appartement. Une fois l’eau coupée, appelez le concierge puis prévenez-moi immédiatement.",
lost_keys: "Si vous perdez les clés, la première chose à faire est de m’appeler immédiatement et de m’en informer afin que je puisse gérer la situation correctement."
    },
    de: {
      wifi: "WLAN: Der Router steht auf dem Schreibtisch nahe dem Fenster. Drehen Sie ihn, um SSID und Passwort auf dem Aufkleber zu lesen. Falls es nicht funktioniert: prüfen Sie, ob er eingeschaltet ist, ziehen Sie den Stecker 30 Sekunden und stecken Sie ihn wieder ein. Dann bitte melden.",
      trash: "Müll: Müllbeutel befinden sich in der Küche. Gut verschließen und vor dem Verlassen in die Tonnen im Innenhof bringen. Mülltrennung ist Pflicht: nichts im Treppenhaus oder vor der Wohnungstür abstellen.Nachdem Sie den Müll getrennt haben, bringen Sie ihn bitte vor dem Check-out in den Außenhof. Vor dem Ausgang, auf der rechten Seite, befinden sich die Müllcontainer. Entsorgen Sie jede Abfallart im entsprechenden Container. Danke.",
      heating: "Heizung: Verwenden Sie die Klimaanlagen-Fernbedienung. MODE drücken bis das Sonnensymbol erscheint, 26 °C und Stufe 1 einstellen. Beim Verlassen immer ausschalten.",
      electric_panel: "Sicherungskasten: Auf dem Weg zum Bad rechts vor der Tür. Bei Stromausfall: 1) heruntergefallene Sicherungen hochstellen; 2) wenn alle oben sind, obere Abdeckung entfernen, Hauptschalter zurücksetzen und einige Geräte ausschalten.",
      check_in: "Check-in ab 15:00 Uhr. Gegensprechanlage C8. Haustür aktiv 08:00–13:00 und 15:30–18:00. Pförtner: Paolo. Hilfe: +39 335 5245756.",
      check_out: "Check-out: Vor der Abreise Licht und Klimaanlage ausschalten, Fenster schließen, Schlüssel auf dem Tisch lassen und die Tür vorsichtig schließen.",
      city_tax_info: "Touristensteuer: In Rom für Nicht-Einwohner verpflichtend. Für diese Wohnung 5 € pro Person und Nacht, maximal 10 Nächte. Wird für die Stadt Rom erhoben.",
      laundry: "Wäscherei: Wenn Sie Kleidung oder Handtücher waschen müssen, schreiben Sie mir – ich empfehle Ihnen die beste Lösung in der Nähe.",
      building: "Gebäude: Gegensprechanlage C8. Aufzug nur für Eigentümer (bitte nicht benutzen). Haustür 08:00–13:00 und 15:30–18:00. Pförtner: Paolo.",
      emergency: "Notfälle: EU 112 • Polizei 113 • Rettung 118 • Feuerwehr 115 • Arzt (EN) +39 06 488 2371 • Tierarzt 24h +39 06 660 681",
      air_conditioning: "Klimaanlage: Verwenden Sie die Fernbedienung. MODE drücken bis das Schneeflocken-Symbol erscheint, 24 °C und auto einstellen. Beim Verlassen immer ausschalten.",
      parking: "Parkplatz: Die Wohnung liegt im historischen Zentrum (ZTL - Verkehrsbeschränkte Zone). Die Zufahrt mit dem Auto ist nur Montag bis Samstag von 19:00 bis 7:30 Uhr erlaubt. Um den nächsten Parkplatz zu finden, suchen Sie die Adresse der Wohnung bei Google Maps. Bei Schwierigkeiten rufen Sie mich an: +39 335 5245756.",
      services: "Für Informationen zu Apotheken, Krankenhäusern, Geldautomaten und anderen Services siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      transport: "Für Informationen zu Transport, Metro, Bussen und Flughäfen siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      restaurants: "Für Empfehlungen zu Restaurants, Pizzerien und Bars siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      shopping: "Für Informationen zu Geschäften und Märkten siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      attractions: "Um zu entdecken, was in Rom zu besuchen ist, siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      day_trips: "Für Informationen zu Tagesausflügen außerhalb Roms siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      tickets: "Für Informationen zu Tickets für Museen, Veranstaltungen und Spiele siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=de",
      gas_leak: "Wenn Sie Gasgeruch wahrnehmen, überprüfen Sie sofort das Gasgerät und stellen Sie sicher, dass alle schwarzen Drehknöpfe auf der rechten Seite geschlossen sind. Vor dem Gasgerät, leicht auf der rechten Seite, befindet sich ein Metallventil: Drehen Sie es nach unten, um die Gaszufuhr vollständig zu schließen. Rufen Sie mich danach bitte sofort an, damit ich die Wohnung überprüfen kann.",
water_leak: "Falls es in der Wohnung zu einem Wasserleck kommt, gehen Sie ins Badezimmer. Wenn Sie in den Spiegel schauen, finden Sie auf der linken Seite nahe der Wandecke eine Metallkappe: Schrauben Sie diese ab. Dahinter befindet sich ein schwarzes Ventil: Schließen Sie es vollständig, da es das Hauptabsperrventil für das Wasser der Wohnung ist. Nachdem das Wasser abgestellt wurde, rufen Sie den Hausmeister an und informieren Sie mich anschließend sofort.",
lost_keys: "Falls Sie die Schlüssel verlieren, rufen Sie mich bitte sofort an und informieren Sie mich, damit ich die Situation korrekt regeln kann."
    },
    es: {
      wifi: "Wi-Fi: El router está en el escritorio cerca de la ventana. Gíralo para leer el SSID y la contraseña en la etiqueta. Si no funciona: comprueba que esté encendido, desenchúfalo 30 segundos y vuelve a conectarlo. Si continúa, escríbeme.",
      trash: "Basura: Las bolsas están en la cocina. Ciérralas bien y llévalas a los contenedores del patio antes de salir. Hacemos reciclaje: sigue las indicaciones y no dejes basura en la escalera ni fuera del apartamento.Una vez separada toda la basura, antes del check-out llévela al patio exterior. Antes de la salida, en el lado derecho, encontrará los contenedores. Deposite cada tipo de residuo en el contenedor correspondiente. Gracias.",
      heating: "Calefacción: Usa el mando del aire acondicionado. Pulsa MODE hasta que aparezca el símbolo del sol, ajusta a 26 °C y potencia 1. Apágalo siempre al salir.",
      electric_panel: "Cuadro eléctrico: Yendo hacia el baño, a la derecha antes de la puerta. Si no hay luz: 1) sube los interruptores bajados; 2) si ya están todos arriba, retira el panel superior, rearma el general y apaga algunos electrodomésticos.",
      check_in: "Check-in desde las 15:00. Portero automático C8. Puerta principal activa 08:00–13:00 y 15:30–18:00. Portero: Paolo. Ayuda: +39 335 5245756.",
      check_out: "Check-out: Antes de salir apaga luces y aire acondicionado, cierra las ventanas, deja las llaves sobre la mesa y cierra la puerta con cuidado.",
      city_tax_info: "Tasa turística: Obligatoria en Roma para no residentes. Para este apartamento es de 5 € por persona y noche, máximo 10 noches. Se cobra en nombre del Ayuntamiento de Roma.",
      laundry: "Lavandería: Si necesitas lavar ropa o toallas, escríbeme y te indicaré la mejor opción cercana según tus horarios.",
      building: "Edificio: Portero automático C8. Ascensor reservado a los propietarios (no usar). Puerta principal 08:00–13:00 y 15:30–18:00. Portero: Paolo.",
      emergency: "Emergencias: UE 112 • Policía 113 • Ambulancia 118 • Bomberos 115 • Médico (EN) +39 06 488 2371 • Veterinario 24h +39 06 660 681",
      air_conditioning: "Aire acondicionado: Usa el mando. Pulsa MODE hasta que aparezca el símbolo del copo de nieve, ajusta a 24 °C y potencia auto. Apágalo siempre al salir.",
      parking: "Aparcamiento: El apartamento está en el centro histórico (ZTL - Zona de Tráfico Limitado). El acceso en coche está permitido solo de lunes a sábado de 19:00 a 7:30. Para encontrar el aparcamiento más cercano, busca la dirección del apartamento en Google Maps. Si tienes dificultades, llámame: +39 335 5245756.",
      services: "Para información sobre farmacias, hospitales, cajeros y otros servicios, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      transport: "Para información sobre transporte, metro, autobuses y aeropuertos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      restaurants: "Para recomendaciones de restaurantes, pizzerías y bares, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      shopping: "Para información sobre tiendas y mercados, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      attractions: "Para descubrir qué visitar en Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      day_trips: "Para información sobre excursiones de un día fuera de Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      tickets: "Para información sobre entradas para museos, eventos y partidos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/arenula/?lang=es",
      gas_leak: "Si sienten olor a gas, revisen inmediatamente la unidad de gas y comprueben que todas las perillas negras del lado derecho estén bien cerradas. Luego, frente a la unidad de gas, ligeramente a la derecha, encontrarán una válvula metálica: gírenla hacia abajo para cerrar completamente el suministro de gas. Después de estas operaciones, llámenme inmediatamente para que pueda revisar el apartamento.",
water_leak: "En caso de una fuga de agua en el apartamento, vayan al baño. Mirando el espejo, en el lado izquierdo cerca de la esquina de la pared, encontrarán un tapón metálico: desenróscanlo. Detrás hay una válvula negra: ciérrenla completamente, ya que es la llave principal del agua del apartamento. Una vez cerrada el agua, llamen al portero y luego avísenme inmediatamente.",
lost_keys: "En caso de que pierdan las llaves, lo primero que deben hacer es llamarme inmediatamente y avisarme para poder gestionar la situación correctamente."
    }
  },

  leonina: {
    it: {
      wifi: "Wi-Fi: Il router è sulla scrivania vicino alla finestra. Giralo per leggere SSID e password sull'etichetta. Se non funziona: controlla che sia acceso, scollegalo 30 secondi e ricollegalo. Se il problema continua, scrivimi.",
      trash: "Spazzatura: Trovi i sacchi in cucina. Chiudili bene e portali nei cassonetti a 50 metri a sinistra dell'uscita del portone. Facciamo raccolta differenziata: segui le indicazioni e non lasciare immondizia nel vano scala o fuori dalla porta.",
      heating: "Riscaldamento: Usa il telecomando dell'aria condizionata, premi MODE finché compare il simbolo del sole e imposta 26 °C con potenza 1. Spegni sempre il condizionatore quando esci.",
      electric_panel: "Quadro elettrico: È sul lato sinistro guardando la porta di uscita dell'appartamento. Se manca la corrente, alza gli interruttori abbassati e spegni qualche elettrodomestico.",
      check_in: "Check-in dalle 15:00. Citofono: interno 16. Codice portone: 7171 + simbolo della chiave. Aiuto: +39 335 5245756.",
      check_out: "Check-out: Prima di partire spegni luci e A/C, chiudi le finestre, lascia le chiavi sul tavolo e chiudi delicatamente la porta verificando che sia ben chiusa.",
      city_tax_info: "Tassa di soggiorno: A Roma è obbligatoria per gli ospiti non residenti. Per questo appartamento è di 6 € a persona per notte, fino a un massimo di 10 notti. La incassiamo per conto del Comune di Roma.",
      laundry: "Lavanderia: Puoi utilizzare la lavatrice in appartamento. In alternativa, scrivimi e ti indico una lavanderia in zona in base ai tuoi orari.",
      building: "Edificio: Citofono interno 16. Ascensore con porte manuali: ricordati di aprirle e chiuderle sempre. L'ascensore arriva al quarto piano; uscendo, l'appartamento è sulla sinistra.",
      emergency: "Emergenze: UE 112 • Polizia 113 • Ambulanza 118 • Vigili del Fuoco 115 • Medico (EN) +39 06 488 2371 • Veterinario 24h +39 06 660 681",
      air_conditioning: "Aria condizionata: Usa il telecomando. Premi MODE finché appare il simbolo del fiocco di neve, imposta 24 °C e potenza auto. Spegni sempre quando esci.",
      parking: "Parcheggio: L'appartamento si trova nel centro storico (ZTL). L'accesso in auto è consentito solo dal lunedì al sabato dalle 19:00 alle 7:30. Per trovare il parcheggio più vicino cerca su Google Maps l'indirizzo dell'appartamento. Se hai difficoltà, chiamami: +39 335 5245756.",
      services: "Per informazioni su farmacie, ospedali, bancomat e altri servizi consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      transport: "Per informazioni su trasporti, metro, bus e aeroporti consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      restaurants: "Per consigli su ristoranti, pizzerie e locali consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      shopping: "Per informazioni su negozi e mercati consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      attractions: "Per scoprire cosa visitare a Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      day_trips: "Per informazioni su gite ed escursioni fuori Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      tickets: "Per informazioni su biglietti per musei, eventi e partite consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=it",
      water_leak: "Nel caso si verifichi una perdita d’acqua, la prima cosa da fare è uscire dall’appartamento. Subito sul lato destro, accanto alla porta, troverete uno sportello: apritelo. All’interno c’è il primo contatore in alto con un rubinetto: chiudetelo completamente, perché è il rubinetto dell’acqua dell’appartamento. Una volta chiusa l’acqua, avvertitemi immediatamente.",
lost_keys: "Nel caso in cui doveste perdere le chiavi, la prima cosa da fare è chiamarmi immediatamente e avvertirmi, così da poter gestire la situazione nel modo corretto."
    },
    en: {
      wifi: "Wi-Fi: The router is on the desk near the window. Turn it to read the SSID and password on the label. If it doesn't work: check it's on, unplug it for 30 seconds and plug it back in. If the issue continues, message me.",
      trash: "Trash: Bags are in the kitchen. Close them well and take them to the bins 50 meters to the left after exiting the building. Recycling is required: follow the signs and do not leave trash in the stairwell or outside the apartment door.",
      heating: "Heating: Use the A/C remote control, press MODE until the SUN symbol appears, set 26 °C and power level 1. Always turn it off when leaving.",
      electric_panel: "Electric panel: Located on the left side when facing the apartment exit door. If there's no power, reset the lowered breakers and turn off some appliances.",
      check_in: "Check-in from 3:00 PM. Intercom: unit 16. Building door code: 7171 + key symbol. Help: +39 335 5245756.",
      check_out: "Check-out: Before leaving, turn off lights and A/C, close the windows, leave the keys on the table and close the door carefully, making sure it is locked.",
      city_tax_info: "City tax: Mandatory in Rome for non-residents. For this apartment it is €6 per person per night, up to a maximum of 10 nights. Collected on behalf of the City of Rome.",
      laundry: "Laundry: You can use the washing machine in the apartment. Alternatively, message me and I'll suggest a nearby laundry option based on your schedule.",
      building: "Building: Intercom unit 16. Elevator has manual doors—please always open and close them. The elevator goes to the 4th floor; when exiting, the apartment is on the left.",
      emergency: "Emergencies: EU 112 • Police 113 • Ambulance 118 • Fire Brigade 115 • Doctor (EN) +39 06 488 2371 • 24h Vet +39 06 660 681",
      air_conditioning: "Air conditioning: Use the remote control. Press MODE until the snowflake symbol appears, set 24 °C and auto power. Always turn it off when leaving.",
      parking: "Parking: The apartment is in the historic center (ZTL - Limited Traffic Zone). Car access is allowed only Monday to Saturday from 7:00 PM to 7:30 AM. To find the nearest parking, search the apartment address on Google Maps. If you need help, call me: +39 335 5245756.",
      services: "For information on pharmacies, hospitals, ATMs and other services, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      transport: "For information on transport, metro, buses and airports, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      restaurants: "For restaurant, pizzeria and bar recommendations, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      shopping: "For information on shops and markets, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      attractions: "To discover what to visit in Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      day_trips: "For information on day trips and excursions outside Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      tickets: "For information on tickets for museums, events and matches, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=en",
      water_leak: "In case of a water leak, the first thing to do is exit the apartment. Immediately on the right side, next to the door, you will find a small cabinet: open it. Inside there is the first meter at the top with a valve: close it completely, as it is the apartment’s water shut-off valve. Once the water is shut off, please inform me immediately.",
lost_keys: "If you lose the keys, the first thing to do is call me immediately and inform me, so I can handle the situation properly."
    },
    fr: {
      wifi: "Wi-Fi : Le routeur est sur le bureau près de la fenêtre. Tournez-le pour lire le SSID et le mot de passe sur l'étiquette. S'il ne fonctionne pas : vérifiez qu'il est allumé, débranchez-le 30 secondes puis rebranchez-le. Sinon, écrivez-moi.",
      trash: "Déchets : Les sacs sont dans la cuisine. Fermez-les bien et jetez-les dans les bacs à 50 mètres à gauche en sortant de l'immeuble. Le tri est obligatoire : suivez les indications et ne laissez rien dans l'escalier ou devant la porte.",
      heating: "Chauffage : Utilisez la télécommande de la climatisation, appuyez sur MODE jusqu'au symbole soleil, réglez à 26 °C et puissance 1. Éteignez toujours en sortant.",
      electric_panel: "Tableau électrique : Situé à gauche en regardant la porte de sortie de l'appartement. En cas de coupure, remontez les disjoncteurs et éteignez quelques appareils.",
      check_in: "Arrivée à partir de 15h00. Interphone : appartement 16. Code porte : 7171 + symbole clé. Aide : +39 335 5245756.",
      check_out: "Départ : Avant de partir, éteignez lumières et climatisation, fermez les fenêtres, laissez les clés sur la table et fermez la porte soigneusement.",
      city_tax_info: "Taxe de séjour : Obligatoire à Rome pour les non-résidents. Pour cet appartement : 6 € par personne et par nuit, maximum 10 nuits. Perçue pour la Ville de Rome.",
      laundry: "Blanchisserie : Vous pouvez utiliser le lave-linge de l'appartement. Sinon, écrivez-moi et je vous indiquerai une solution à proximité.",
      building: "Immeuble : Interphone appartement 16. Ascenseur à portes manuelles — merci de toujours les ouvrir et fermer. L'ascenseur arrive au 4e étage ; en sortant, l'appartement est à gauche.",
      emergency: "Urgences : UE 112 • Police 113 • Ambulance 118 • Pompiers 115 • Médecin (EN) +39 06 488 2371 • Vétérinaire 24h +39 06 660 681",
      air_conditioning: "Climatisation : Utilisez la télécommande. Appuyez sur MODE jusqu'au symbole flocon, réglez à 24 °C et puissance auto. Éteignez toujours en sortant.",
      parking: "Parking : L'appartement se trouve dans le centre historique (ZTL - Zone à Trafic Limité). L'accès en voiture est autorisé uniquement du lundi au samedi de 19h00 à 7h30. Pour trouver le parking le plus proche, recherchez l'adresse de l'appartement sur Google Maps. En cas de difficulté, appelez-moi : +39 335 5245756.",
      services: "Pour les informations sur pharmacies, hôpitaux, distributeurs et autres services, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      transport: "Pour les informations sur transports, métro, bus et aéroports, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      restaurants: "Pour les recommandations de restaurants, pizzerias et bars, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      shopping: "Pour les informations sur magasins et marchés, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      attractions: "Pour découvrir quoi visiter à Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      day_trips: "Pour les informations sur excursions d'une journée hors de Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      tickets: "Pour les informations sur billets pour musées, événements et matchs, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=fr",
      water_leak: "En cas de fuite d’eau, la première chose à faire est de sortir de l’appartement. Immédiatement sur le côté droit, près de la porte, vous trouverez un coffret : ouvrez-le. À l’intérieur se trouve le premier compteur en haut avec un robinet : fermez-le complètement, car il s’agit de la vanne d’eau de l’appartement. Une fois l’eau coupée, prévenez-moi immédiatement.",
lost_keys: "Si vous perdez les clés, la première chose à faire est de m’appeler immédiatement et de m’en informer afin que je puisse gérer la situation correctement."
    },
    de: {
      wifi: "WLAN: Der Router steht auf dem Schreibtisch nahe dem Fenster. Drehen Sie ihn, um SSID und Passwort auf dem Aufkleber zu lesen. Falls es nicht funktioniert: prüfen Sie, ob er eingeschaltet ist, ziehen Sie den Stecker 30 Sekunden und stecken Sie ihn wieder ein. Dann bitte melden.",
      trash: "Müll: Müllbeutel befinden sich in der Küche. Gut verschließen und 50 Meter links vom Hauseingang in die Tonnen bringen. Mülltrennung ist Pflicht: nichts im Treppenhaus oder vor der Wohnungstür abstellen.",
      heating: "Heizung: Verwenden Sie die Klimaanlagen-Fernbedienung, MODE drücken bis das Sonnensymbol erscheint, 26 °C und Stufe 1 einstellen. Beim Verlassen immer ausschalten.",
      electric_panel: "Sicherungskasten: Befindet sich links, wenn man zur Ausgangstür blickt. Bei Stromausfall Sicherungen hochstellen und einige Geräte ausschalten.",
      check_in: "Check-in ab 15:00 Uhr. Gegensprechanlage: Wohnung 16. Haustürcode: 7171 + Schlüsselsymbol. Hilfe: +39 335 5245756.",
      check_out: "Check-out: Vor der Abreise Licht und Klimaanlage ausschalten, Fenster schließen, Schlüssel auf dem Tisch lassen und die Tür sorgfältig schließen.",
      city_tax_info: "Touristensteuer: In Rom für Nicht-Einwohner verpflichtend. Für diese Wohnung 6 € pro Person und Nacht, maximal 10 Nächte. Wird für die Stadt Rom erhoben.",
      laundry: "Wäscherei: Waschmaschine in der Wohnung vorhanden. Alternativ schreiben Sie mir für eine Empfehlung in der Nähe.",
      building: "Gebäude: Gegensprechanlage Wohnung 16. Aufzug mit manuellen Türen — bitte immer öffnen und schließen. Der Aufzug fährt bis in den 4. Stock; beim Aussteigen ist die Wohnung links.",
      emergency: "Notfälle: EU 112 • Polizei 113 • Rettung 118 • Feuerwehr 115 • Arzt (EN) +39 06 488 2371 • Tierarzt 24h +39 06 660 681",
      air_conditioning: "Klimaanlage: Verwenden Sie die Fernbedienung. MODE drücken bis das Schneeflocken-Symbol erscheint, 24 °C und auto einstellen. Beim Verlassen immer ausschalten.",
      parking: "Parkplatz: Die Wohnung liegt im historischen Zentrum (ZTL - Verkehrsbeschränkte Zone). Die Zufahrt mit dem Auto ist nur Montag bis Samstag von 19:00 bis 7:30 Uhr erlaubt. Um den nächsten Parkplatz zu finden, suchen Sie die Adresse der Wohnung bei Google Maps. Bei Schwierigkeiten rufen Sie mich an: +39 335 5245756.",
      services: "Für Informationen zu Apotheken, Krankenhäusern, Geldautomaten und anderen Services siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      transport: "Für Informationen zu Transport, Metro, Bussen und Flughäfen siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      restaurants: "Für Empfehlungen zu Restaurants, Pizzerien und Bars siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      shopping: "Für Informationen zu Geschäften und Märkten siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      attractions: "Um zu entdecken, was in Rom zu besuchen ist, siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      day_trips: "Für Informationen zu Tagesausflügen außerhalb Roms siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      tickets: "Für Informationen zu Tickets für Museen, Veranstaltungen und Spiele siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=de",
      water_leak: "Falls es zu einem Wasserleck kommt, verlassen Sie zuerst die Wohnung. Direkt auf der rechten Seite, neben der Tür, befindet sich ein kleiner Schrank: öffnen Sie ihn. Darin finden Sie oben den ersten Zähler mit einem Ventil: schließen Sie es vollständig, da es sich um das Wasserabsperrventil der Wohnung handelt. Nachdem das Wasser abgestellt wurde, informieren Sie mich bitte sofort.",
lost_keys: "Falls Sie die Schlüssel verlieren, rufen Sie mich bitte sofort an und informieren Sie mich, damit ich die Situation korrekt regeln kann."
    },
    es: {
      wifi: "Wi-Fi: El router está en el escritorio cerca de la ventana. Gíralo para leer el SSID y la contraseña en la etiqueta. Si no funciona: comprueba que esté encendido, desenchúfalo 30 segundos y vuelve a conectarlo. Si continúa, escríbeme.",
      trash: "Basura: Las bolsas están en la cocina. Ciérralas bien y llévalas a los contenedores a 50 metros a la izquierda al salir del edificio. El reciclaje es obligatorio: sigue las indicaciones y no dejes basura en la escalera ni fuera del apartamento.",
      heating: "Calefacción: Usa el mando del aire acondicionado, pulsa MODE hasta que aparezca el símbolo del sol, ajusta a 26 °C y potencia 1. Apágalo siempre al salir.",
      electric_panel: "Cuadro eléctrico: Está a la izquierda mirando la puerta de salida del apartamento. Si no hay luz, sube los interruptores bajados y apaga algunos electrodomésticos.",
      check_in: "Check-in desde las 15:00. Portero automático: piso 16. Código del portal: 7171 + símbolo de la llave. Ayuda: +39 335 5245756.",
      check_out: "Check-out: Antes de salir apaga luces y aire acondicionado, cierra las ventanas, deja las llaves sobre la mesa y cierra la puerta con cuidado.",
      city_tax_info: "Tasa turística: Obligatoria en Roma para no residentes. Para este apartamento es de 6 € por persona y noche, máximo 10 noches. Se cobra en nombre del Ayuntamiento de Roma.",
      laundry: "Lavandería: Puedes usar la lavadora del apartamento. Si lo prefieres, escríbeme y te indicaré una lavandería cercana.",
      building: "Edificio: Portero automático piso 16. Ascensor con puertas manuales — recuerda abrirlas y cerrarlas siempre. Llega hasta la 4ª planta; al salir, el apartamento está a la izquierda.",
      emergency: "Emergencias: UE 112 • Policía 113 • Ambulancia 118 • Bomberos 115 • Médico (EN) +39 06 488 2371 • Veterinario 24h +39 06 660 681",
      air_conditioning: "Aire acondicionado: Usa el mando. Pulsa MODE hasta que aparezca el símbolo del copo de nieve, ajusta a 24 °C y potencia auto. Apágalo siempre al salir.",
      parking: "Aparcamiento: El apartamento está en el centro histórico (ZTL - Zona de Tráfico Limitado). El acceso en coche está permitido solo de lunes a sábado de 19:00 a 7:30. Para encontrar el aparcamiento más cercano, busca la dirección del apartamento en Google Maps. Si tienes dificultades, llámame: +39 335 5245756.",
      services: "Para información sobre farmacias, hospitales, cajeros y otros servicios, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      transport: "Para información sobre transporte, metro, autobuses y aeropuertos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      restaurants: "Para recomendaciones de restaurantes, pizzerías y bares, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      shopping: "Para información sobre tiendas y mercados, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      attractions: "Para descubrir qué visitar en Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      day_trips: "Para información sobre excursiones de un día fuera de Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      tickets: "Para información sobre entradas para museos, eventos y partidos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/leonina/?lang=es",
      water_leak: "En caso de una fuga de agua, lo primero que deben hacer es salir del apartamento. Inmediatamente a la derecha, junto a la puerta, encontrarán un armario: ábranlo. Dentro se encuentra el primer contador en la parte superior con una llave: ciérrenla completamente, ya que es la llave de paso del agua del apartamento. Una vez cerrada el agua, avísenme inmediatamente.",
lost_keys: "En caso de que pierdan las llaves, lo primero que deben hacer es llamarme inmediatamente y avisarme para poder gestionar la situación correctamente."
    }
  },

  scala: {
    it: {
      wifi: "Wi-Fi: Il router si trova sul lato destro del soggiorno, appoggiato su una panca. SSID e password sono indicati sull'etichetta del router. Se non funziona: controlla che sia acceso, scollegalo 30 secondi e ricollegalo. Se il problema continua, scrivimi.",
      trash: "Spazzatura: Prima di lasciare l'appartamento, butta i rifiuti negli appositi cestini. Facciamo raccolta differenziata: porta i sacchetti a fine Via della Scala, angolo Via Garibaldi, tutti i giorni dalle 8:00 alle 9:30.",
      heating: "Riscaldamento: Per accenderlo vai in camera da letto. Guardando la finestra, sulla sinistra trovi un piccolo termostato: porta l'interruttore su ON e imposta la ghiera a 26 °C. Dopo pochi minuti i termosifoni iniziano a scaldarsi.",
      electric_panel: "Quadro elettrico: Se salta la corrente, uscendo dall'appartamento il quadro è sulla destra. Controlla che tutti gli interruttori siano verso l'alto. Se la corrente non torna, sopra il quadro c'è uno sportello in legno: aprilo e rialza anche l'interruttore generale.",
      check_in: "Check-in dalle 15:00. Citofono esterno: colonna sinistra, primo pulsante dal basso. Citofono interno: A/1.",
      check_out: "Check-out: Prima di partire spegni le luci, chiudi le finestre, lascia le chiavi sul tavolo e chiudi la porta verificando che sia ben chiusa.",
      city_tax_info: "Tassa di soggiorno: A Roma è prevista per gli ospiti non residenti. Per questo appartamento è di 5 € a persona per notte, fino a un massimo di 10 notti. La riscuotiamo per conto del Comune di Roma.",
      laundry: "Lavanderia: Se hai bisogno di lavare vestiti o asciugamani, scrivimi e ti indico la soluzione migliore in zona Trastevere in base ai tuoi orari.",
      building: "Edificio: Appartamento in zona Trastevere, quartiere vivace e centrale. Accesso tramite portone con citofono esterno e interno.",
      emergency: "Emergenze: UE 112 • Polizia 113 • Ambulanza 118 • Vigili del Fuoco 115",
      air_conditioning: "Aria condizionata: Usa il telecomando. Premi MODE finché appare il simbolo del fiocco di neve, imposta 24 °C e potenza auto. Spegni sempre quando esci.",
      parking: "Parcheggio: L'appartamento si trova nel centro storico (ZTL). L'accesso in auto è consentito solo dal lunedì al sabato dalle 19:00 alle 7:30. Per trovare il parcheggio più vicino cerca su Google Maps l'indirizzo dell'appartamento. Se hai difficoltà, chiamami: +39 335 5245756.",
      services: "Per informazioni su farmacie, ospedali, bancomat e altri servizi consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it",
      transport: "Per informazioni su trasporti, metro, bus e aeroporti consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it",
      restaurants: "Per consigli su ristoranti, pizzerie e locali consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it",
      shopping: "Per informazioni su negozi e mercati consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it",
      attractions: "Per scoprire cosa visitare a Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it",
      day_trips: "Per informazioni su gite ed escursioni fuori Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it",
      tickets: "Per informazioni su biglietti per musei, eventi e partite consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=it"
    },
    en: {
      wifi: "Wi-Fi: The router is on the right side of the living room, placed on a bench. SSID and password are on the router label. If it doesn't work: check it's on, unplug it for 30 seconds and plug it back in. If the issue continues, message me.",
      trash: "Trash: Before leaving, dispose of waste in the designated bins. Recycling is required: take the bags to the end of Via della Scala, corner with Via Garibaldi, every day from 8:00 to 9:30.",
      heating: "Heating: To turn it on, go to the bedroom. Facing the window, on the left you'll find a small thermostat: switch it to ON and set 26 °C. After a few minutes the radiators will warm up.",
      electric_panel: "Electric panel: If the power goes out, the panel is on the right when exiting the apartment. Make sure all breakers are up. If power doesn't return, above the panel there's a wooden hatch—open it and reset the main switch.",
      check_in: "Check-in from 3:00 PM. External intercom: left column, first button from the bottom. Internal intercom: A/1.",
      check_out: "Check-out: Before leaving, turn off lights, close the windows, leave the keys on the table and close the door, making sure it's properly locked.",
      city_tax_info: "City tax: Required in Rome for non-residents. For this apartment it is €5 per person per night, up to a maximum of 10 nights. Collected on behalf of the City of Rome.",
      laundry: "Laundry: If you need to wash clothes or towels, message me and I'll suggest the best option in the Trastevere area.",
      building: "Building: Apartment located in the Trastevere district, lively and central. Access via building door with external and internal intercom.",
      emergency: "Emergencies: EU 112 • Police 113 • Ambulance 118 • Fire Brigade 115",
      air_conditioning: "Air conditioning: Use the remote control. Press MODE until the snowflake symbol appears, set 24 °C and auto power. Always turn it off when leaving.",
      parking: "Parking: The apartment is in the historic center (ZTL - Limited Traffic Zone). Car access is allowed only Monday to Saturday from 7:00 PM to 7:30 AM. To find the nearest parking, search the apartment address on Google Maps. If you need help, call me: +39 335 5245756.",
      services: "For information on pharmacies, hospitals, ATMs and other services, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en",
      transport: "For information on transport, metro, buses and airports, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en",
      restaurants: "For restaurant, pizzeria and bar recommendations, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en",
      shopping: "For information on shops and markets, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en",
      attractions: "To discover what to visit in Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en",
      day_trips: "For information on day trips and excursions outside Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en",
      tickets: "For information on tickets for museums, events and matches, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=en"
    },
    fr: {
      wifi: "Wi-Fi : Le routeur se trouve à droite du salon, posé sur un banc. Le SSID et le mot de passe sont indiqués sur l'étiquette. En cas de problème : vérifiez qu'il est allumé, débranchez-le 30 secondes puis rebranchez-le.",
      trash: "Déchets : Avant de partir, jetez les déchets dans les bacs prévus. Tri obligatoire : déposez les sacs au bout de la Via della Scala, angle Via Garibaldi, tous les jours de 8h00 à 9h30.",
      heating: "Chauffage : Pour l'allumer, allez dans la chambre. Face à la fenêtre, à gauche se trouve un petit thermostat : mettez-le sur ON et réglez à 26 °C. Les radiateurs chauffent après quelques minutes.",
      electric_panel: "Tableau électrique : En cas de coupure, le tableau est à droite en sortant de l'appartement. Vérifiez que tous les interrupteurs sont levés. Si nécessaire, ouvrez la trappe en bois au-dessus et réarmez l'interrupteur général.",
      check_in: "Arrivée à partir de 15h00. Interphone extérieur : colonne gauche, premier bouton en bas. Interphone intérieur : A/1.",
      check_out: "Départ : Avant de partir, éteignez les lumières, fermez les fenêtres, laissez les clés sur la table et fermez la porte correctement.",
      city_tax_info: "Taxe de séjour : Obligatoire à Rome pour les non-résidents. Pour cet appartement : 5 € par personne et par nuit, maximum 10 nuits. Perçue pour la Ville de Rome.",
      laundry: "Blanchisserie : Si vous devez laver des vêtements ou serviettes, écrivez-moi et je vous indiquerai la meilleure solution à Trastevere.",
      building: "Immeuble : Appartement situé dans le quartier de Trastevere, animé et central. Accès par porte avec interphone extérieur et intérieur.",
      emergency: "Urgences : UE 112 • Police 113 • Ambulance 118 • Pompiers 115",
      air_conditioning: "Climatisation : Utilisez la télécommande. Appuyez sur MODE jusqu'au symbole flocon, réglez à 24 °C et puissance auto. Éteignez toujours en sortant.",
      parking: "Parking : L'appartement se trouve dans le centre historique (ZTL - Zone à Trafic Limité). L'accès en voiture est autorisé uniquement du lundi au samedi de 19h00 à 7h30. Pour trouver le parking le plus proche, recherchez l'adresse de l'appartement sur Google Maps. En cas de difficulté, appelez-moi : +39 335 5245756.",
      services: "Pour les informations sur pharmacies, hôpitaux, distributeurs et autres services, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr",
      transport: "Pour les informations sur transports, métro, bus et aéroports, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr",
      restaurants: "Pour les recommandations de restaurants, pizzerias et bars, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr",
      shopping: "Pour les informations sur magasins et marchés, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr",
      attractions: "Pour découvrir quoi visiter à Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr",
      day_trips: "Pour les informations sur excursions d'une journée hors de Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr",
      tickets: "Pour les informations sur billets pour musées, événements et matchs, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=fr"
    },
    de: {
      wifi: "WLAN: Der Router steht auf der rechten Seite des Wohnzimmers auf einer Bank. SSID und Passwort stehen auf dem Aufkleber. Bei Problemen: prüfen, ob er eingeschaltet ist, 30 Sekunden vom Strom trennen und wieder anschließen.",
      trash: "Müll: Vor der Abreise den Müll in die vorgesehenen Tonnen bringen. Mülltrennung ist Pflicht: Abgabe am Ende der Via della Scala, Ecke Via Garibaldi, täglich von 8:00 bis 9:30.",
      heating: "Heizung: Zum Einschalten ins Schlafzimmer gehen. Mit Blick zum Fenster befindet sich links ein kleiner Thermostat: auf ON stellen und 26 °C einstellen. Nach wenigen Minuten werden die Heizkörper warm.",
      electric_panel: "Sicherungskasten: Bei Stromausfall befindet sich der Kasten rechts beim Verlassen der Wohnung. Alle Schalter müssen oben sein. Falls nötig, die Holzklappe darüber öffnen und den Hauptschalter hochstellen.",
      check_in: "Check-in ab 15:00 Uhr. Außensprechanlage: linke Säule, erster Knopf von unten. Innensprechanlage: A/1.",
      check_out: "Check-out: Vor der Abreise Licht ausschalten, Fenster schließen, Schlüssel auf dem Tisch lassen und die Tür sorgfältig schließen.",
      city_tax_info: "Touristensteuer: In Rom für Nicht-Einwohner verpflichtend. Für diese Wohnung 5 € pro Person und Nacht, maximal 10 Nächte. Wird für die Stadt Rom erhoben.",
      laundry: "Wäscherei: Wenn Sie Kleidung oder Handtücher waschen müssen, schreiben Sie mir – ich empfehle eine Lösung in Trastevere.",
      building: "Gebäude: Wohnung im Stadtteil Trastevere, lebendig und zentral. Zugang über Haustür mit Außen- und Innensprechanlage.",
      emergency: "Notfälle: EU 112 • Polizei 113 • Rettung 118 • Feuerwehr 115",
      air_conditioning: "Klimaanlage: Verwenden Sie die Fernbedienung. MODE drücken bis das Schneeflocken-Symbol erscheint, 24 °C und auto einstellen. Beim Verlassen immer ausschalten.",
      parking: "Parkplatz: Die Wohnung liegt im historischen Zentrum (ZTL - Verkehrsbeschränkte Zone). Die Zufahrt mit dem Auto ist nur Montag bis Samstag von 19:00 bis 7:30 Uhr erlaubt. Um den nächsten Parkplatz zu finden, suchen Sie die Adresse der Wohnung bei Google Maps. Bei Schwierigkeiten rufen Sie mich an: +39 335 5245756.",
      services: "Für Informationen zu Apotheken, Krankenhäusern, Geldautomaten und anderen Services siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de",
      transport: "Für Informationen zu Transport, Metro, Bussen und Flughäfen siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de",
      restaurants: "Für Empfehlungen zu Restaurants, Pizzerien und Bars siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de",
      shopping: "Für Informationen zu Geschäften und Märkten siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de",
      attractions: "Um zu entdecken, was in Rom zu besuchen ist, siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de",
      day_trips: "Für Informationen zu Tagesausflügen außerhalb Roms siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de",
      tickets: "Für Informationen zu Tickets für Museen, Veranstaltungen und Spiele siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=de"
    },
    es: {
      wifi: "Wi-Fi: El router está en el lado derecho del salón, sobre un banco. El SSID y la contraseña están en la etiqueta. Si hay problemas: comprueba que esté encendido, desenchúfalo 30 segundos y vuelve a conectarlo.",
      trash: "Basura: Antes de salir, tira los residuos en los contenedores indicados. Reciclaje obligatorio: lleva las bolsas al final de Via della Scala, esquina con Via Garibaldi, todos los días de 8:00 a 9:30.",
      heating: "Calefacción: Para encenderla ve al dormitorio. Mirando a la ventana, a la izquierda hay un pequeño termostato: ponlo en ON y ajusta a 26 °C. En pocos minutos los radiadores se calientan.",
      electric_panel: "Cuadro eléctrico: Si se corta la luz, el cuadro está a la derecha al salir del apartamento. Comprueba que todos los interruptores estén arriba. Si hace falta, abre la trampilla de madera encima y rearma el general.",
      check_in: "Check-in desde las 15:00. Portero automático exterior: columna izquierda, primer botón desde abajo. Portero automático interior: A/1.",
      check_out: "Check-out: Antes de salir apaga las luces, cierra las ventanas, deja las llaves sobre la mesa y cierra bien la puerta.",
      city_tax_info: "Tasa turística: Obligatoria en Roma para no residentes. Para este apartamento es de 5 € por persona y noche, máximo 10 noches. Se cobra en nombre del Ayuntamiento de Roma.",
      laundry: "Lavandería: Si necesitas lavar ropa o toallas, escríbeme y te indicaré la mejor opción en la zona de Trastevere.",
      building: "Edificio: Apartamento situado en el barrio de Trastevere, céntrico y animado. Acceso mediante puerta con portero automático exterior e interior.",
      emergency: "Emergencias: UE 112 • Policía 113 • Ambulancia 118 • Bomberos 115",
      air_conditioning: "Aire acondicionado: Usa el mando. Pulsa MODE hasta que aparezca el símbolo del copo de nieve, ajusta a 24 °C y potencia auto. Apágalo siempre al salir.",
      parking: "Aparcamiento: El apartamento está en el centro histórico (ZTL - Zona de Tráfico Limitado). El acceso en coche está permitido solo de lunes a sábado de 19:00 a 7:30. Para encontrar el aparcamiento más cercano, busca la dirección del apartamento en Google Maps. Si tienes dificultades, llámame: +39 335 5245756.",
      services: "Para información sobre farmacias, hospitales, cajeros y otros servicios, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es",
      transport: "Para información sobre transporte, metro, autobuses y aeropuertos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es",
      restaurants: "Para recomendaciones de restaurantes, pizzerías y bares, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es",
      shopping: "Para información sobre tiendas y mercados, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es",
      attractions: "Para descubrir qué visitar en Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es",
      day_trips: "Para información sobre excursiones de un día fuera de Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es",
      tickets: "Para información sobre entradas para museos, eventos y partidos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/scala/?lang=es"
    }
  },

  portico: {
    it: {
      wifi: "Wi-Fi: Il router è sul tavolo. Giralo per leggere SSID e password sull'etichetta. Se non funziona: controlla che sia acceso, scollegalo 30 secondi e ricollegalo. Se il problema continua, scrivimi.",
      trash: "Spazzatura: Prima di lasciare l'appartamento, chiudi bene i sacchetti e portali all'isola ecologica di fronte a Piazza delle Cinque Scole (lato Lungotevere). Facciamo raccolta differenziata: segui le indicazioni e non lasciare rifiuti nel vano scala o fuori dalla porta.",
      heating: "Riscaldamento: L'appartamento ha una stufa elettrica. Usala solo quando sei in casa e spegnila sempre quando esci, per motivi di sicurezza.",
      electric_panel: "Quadro elettrico: Se manca la corrente, trovi il quadro sulla destra prima della porta d'uscita dell'appartamento: tutti gli interruttori (incluso il piccolo bianco) devono essere verso l'alto. Se il problema continua, all'uscita del palazzo, sulla sinistra prima della porta d'ingresso, apri lo sportello del tuo contatore e rialza l'interruttore abbassato.",
      check_in: "Check-in dalle 15:00. Accesso tramite Virtual Key: il link apre portone e porta dell'appartamento. Dentro trovi le chiavi sul tavolo; dopo l'ingresso la Virtual Key viene disattivata. Aiuto: +39 335 5245756.",
      check_out: "Check-out: Prima di partire spegni luci e riscaldamento, chiudi le finestre, lascia le chiavi sul tavolo e chiudi manualmente la porta verificando che sia ben chiusa.",
      city_tax_info: "Tassa di soggiorno: A Roma è obbligatoria per gli ospiti non residenti. Per questo appartamento è di 5 € a persona per notte, fino a un massimo di 10 notti. La incassiamo per conto del Comune di Roma.",
      laundry: "Lavanderia: Se devi lavare vestiti o asciugamani, scrivimi e ti indico la soluzione migliore in zona in base ai tuoi orari.",
      building: "Edificio: Accesso tramite portone con Virtual Key. Area Ghetto/Portico d'Ottavia, zona centrale e pedonale in alcune fasce orarie.",
      emergency: "Emergenze: UE 112 • Polizia 113 • Ambulanza 118 • Vigili del Fuoco 115",
      air_conditioning: "Aria condizionata: Usa il telecomando. Premi MODE finché appare il simbolo del fiocco di neve, imposta 24 °C e potenza auto. Spegni sempre quando esci.",
      parking: "Parcheggio: L'appartamento si trova nel centro storico (ZTL). L'accesso in auto è consentito solo dal lunedì al sabato dalle 19:00 alle 7:30. Per trovare il parcheggio più vicino cerca su Google Maps l'indirizzo dell'appartamento. Se hai difficoltà, chiamami: +39 335 5245756.",
      services: "Per informazioni su farmacie, ospedali, bancomat e altri servizi consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it",
      transport: "Per informazioni su trasporti, metro, bus e aeroporti consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it",
      restaurants: "Per consigli su ristoranti, pizzerie e locali consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it",
      shopping: "Per informazioni su negozi e mercati consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it",
      attractions: "Per scoprire cosa visitare a Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it",
      day_trips: "Per informazioni su gite ed escursioni fuori Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it",
      tickets: "Per informazioni su biglietti per musei, eventi e partite consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=it"
    },
    en: {
      wifi: "Wi-Fi: The router is on the table. Turn it to read the SSID and password on the label. If it doesn't work: check it's on, unplug it for 30 seconds and plug it back in. If the issue continues, message me.",
      trash: "Trash: Before leaving the apartment, close the bags well and take them to the recycling area in front of Piazza delle Cinque Scole (Lungotevere side). Recycling is required: follow the signs and do not leave trash in the stairwell or outside the door.",
      heating: "Heating: The apartment has an electric heater. Use it only when you are inside and always turn it off when leaving for safety reasons.",
      electric_panel: "Electric panel: If there is no power, the panel is on the right before the apartment exit door. All switches (including the small white one) must be up. If the issue continues, outside the building on the left before the entrance door, open your meter box and reset the lowered switch.",
      check_in: "Check-in from 3:00 PM. Access via Virtual Key: the link opens both the building door and the apartment door. Inside you'll find the physical keys on the table; after entry the Virtual Key is deactivated. Help: +39 335 5245756.",
      check_out: "Check-out: Before leaving, turn off lights and heating, close the windows, leave the keys on the table and close the door manually, making sure it is properly locked.",
      city_tax_info: "City tax: Mandatory in Rome for non-residents. For this apartment it is €5 per person per night, up to a maximum of 10 nights. Collected on behalf of the City of Rome.",
      laundry: "Laundry: If you need to wash clothes or towels, message me and I'll suggest the best nearby option based on your schedule.",
      building: "Building: Access via building door with Virtual Key. Located in the Ghetto/Portico d'Ottavia area, central and partially pedestrian.",
      emergency: "Emergencies: EU 112 • Police 113 • Ambulance 118 • Fire Brigade 115",
      air_conditioning: "Air conditioning: Use the remote control. Press MODE until the snowflake symbol appears, set 24 °C and auto power. Always turn it off when leaving.",
      parking: "Parking: The apartment is in the historic center (ZTL - Limited Traffic Zone). Car access is allowed only Monday to Saturday from 7:00 PM to 7:30 AM. To find the nearest parking, search the apartment address on Google Maps. If you need help, call me: +39 335 5245756.",
      services: "For information on pharmacies, hospitals, ATMs and other services, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en",
      transport: "For information on transport, metro, buses and airports, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en",
      restaurants: "For restaurant, pizzeria and bar recommendations, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en",
      shopping: "For information on shops and markets, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en",
      attractions: "To discover what to visit in Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en",
      day_trips: "For information on day trips and excursions outside Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en",
      tickets: "For information on tickets for museums, events and matches, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=en"
    },
    fr: {
      wifi: "Wi-Fi : Le routeur est sur la table. Tournez-le pour lire le SSID et le mot de passe sur l'étiquette. S'il ne fonctionne pas : vérifiez qu'il est allumé, débranchez-le 30 secondes puis rebranchez-le. Sinon, écrivez-moi.",
      trash: "Déchets : Avant de partir, fermez bien les sacs et déposez-les à l'aire de tri en face de la Piazza delle Cinque Scole (côté Lungotevere). Le tri est obligatoire : suivez les indications et ne laissez rien dans l'escalier ou devant la porte.",
      heating: "Chauffage : L'appartement est équipé d'un chauffage électrique. Utilisez-le uniquement lorsque vous êtes à l'intérieur et éteignez-le toujours en sortant.",
      electric_panel: "Tableau électrique : En cas de coupure, le tableau se trouve à droite avant la porte de sortie. Tous les interrupteurs (y compris le petit blanc) doivent être relevés. Si le problème persiste, à l'extérieur de l'immeuble sur la gauche, ouvrez le boîtier de votre compteur et réarmez l'interrupteur.",
      check_in: "Arrivée à partir de 15h00. Accès via Virtual Key : le lien ouvre le portail et la porte de l'appartement. À l'intérieur, vous trouverez les clés sur la table ; après l'entrée, la Virtual Key est désactivée. Aide : +39 335 5245756.",
      check_out: "Départ : Avant de partir, éteignez lumières et chauffage, fermez les fenêtres, laissez les clés sur la table et fermez la porte manuellement en vérifiant qu'elle est bien fermée.",
      city_tax_info: "Taxe de séjour : Obligatoire à Rome pour les non-résidents. Pour cet appartement : 5 € par personne et par nuit, maximum 10 nuits. Perçue pour la Ville de Rome.",
      laundry: "Blanchisserie : Si vous devez laver des vêtements ou serviettes, écrivez-moi et je vous indiquerai la meilleure solution à proximité.",
      building: "Immeuble : Accès par porte avec Virtual Key. Situé dans le quartier du Ghetto/Portico d'Ottavia, zone centrale partiellement piétonne.",
      emergency: "Urgences : UE 112 • Police 113 • Ambulance 118 • Pompiers 115",
      air_conditioning: "Climatisation : Utilisez la télécommande. Appuyez sur MODE jusqu'au symbole flocon, réglez à 24 °C et puissance auto. Éteignez toujours en sortant.",
      parking: "Parking : L'appartement se trouve dans le centre historique (ZTL - Zone à Trafic Limité). L'accès en voiture est autorisé uniquement du lundi au samedi de 19h00 à 7h30. Pour trouver le parking le plus proche, recherchez l'adresse de l'appartement sur Google Maps. En cas de difficulté, appelez-moi : +39 335 5245756.",
      services: "Pour les informations sur pharmacies, hôpitaux, distributeurs et autres services, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr",
      transport: "Pour les informations sur transports, métro, bus et aéroports, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr",
      restaurants: "Pour les recommandations de restaurants, pizzerias et bars, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr",
      shopping: "Pour les informations sur magasins et marchés, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr",
      attractions: "Pour découvrir quoi visiter à Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr",
      day_trips: "Pour les informations sur excursions d'une journée hors de Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr",
      tickets: "Pour les informations sur billets pour musées, événements et matchs, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=fr"
    },
    de: {
      wifi: "WLAN: Der Router steht auf dem Tisch. Drehen Sie ihn, um SSID und Passwort auf dem Aufkleber zu lesen. Falls es nicht funktioniert: prüfen Sie, ob er eingeschaltet ist, ziehen Sie den Stecker 30 Sekunden und stecken Sie ihn wieder ein. Dann bitte melden.",
      trash: "Müll: Vor der Abreise die Beutel gut verschließen und zur Recyclingstelle gegenüber der Piazza delle Cinque Scole (Lungotevere-Seite) bringen. Mülltrennung ist Pflicht: nichts im Treppenhaus oder vor der Tür abstellen.",
      heating: "Heizung: Die Wohnung hat einen elektrischen Heizkörper. Nur benutzen, wenn Sie in der Wohnung sind, und beim Verlassen immer ausschalten.",
      electric_panel: "Sicherungskasten: Bei Stromausfall befindet sich der Kasten rechts vor der Wohnungstür. Alle Schalter (auch der kleine weiße) müssen oben sein. Falls das Problem bleibt, draußen links vor dem Eingang den Zählerkasten öffnen und den Schalter hochstellen.",
      check_in: "Check-in ab 15:00 Uhr. Zugang über Virtual Key: Der Link öffnet Haustür und Wohnungstür. Drinnen liegen die Schlüssel auf dem Tisch; danach wird der Virtual Key deaktiviert. Hilfe: +39 335 5245756.",
      check_out: "Check-out: Vor der Abreise Licht und Heizung ausschalten, Fenster schließen, Schlüssel auf dem Tisch lassen und die Tür manuell schließen und prüfen.",
      city_tax_info: "Touristensteuer: In Rom für Nicht-Einwohner verpflichtend. Für diese Wohnung 5 € pro Person und Nacht, maximal 10 Nächte. Wird für die Stadt Rom erhoben.",
      laundry: "Wäscherei: Wenn Sie Kleidung oder Handtücher waschen müssen, schreiben Sie mir für eine Empfehlung in der Nähe.",
      building: "Gebäude: Zugang über Haustür mit Virtual Key. Lage im Ghetto/Portico-d'Ottavia-Viertel, zentrale Lage mit teilweiser Fußgängerzone.",
      emergency: "Notfälle: EU 112 • Polizei 113 • Rettung 118 • Feuerwehr 115",
      air_conditioning: "Klimaanlage: Verwenden Sie die Fernbedienung. MODE drücken bis das Schneeflocken-Symbol erscheint, 24 °C und auto einstellen. Beim Verlassen immer ausschalten.",
      parking: "Parkplatz: Die Wohnung liegt im historischen Zentrum (ZTL - Verkehrsbeschränkte Zone). Die Zufahrt mit dem Auto ist nur Montag bis Samstag von 19:00 bis 7:30 Uhr erlaubt. Um den nächsten Parkplatz zu finden, suchen Sie die Adresse der Wohnung bei Google Maps. Bei Schwierigkeiten rufen Sie mich an: +39 335 5245756.",
      services: "Für Informationen zu Apotheken, Krankenhäusern, Geldautomaten und anderen Services siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de",
      transport: "Für Informationen zu Transport, Metro, Bussen und Flughäfen siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de",
      restaurants: "Für Empfehlungen zu Restaurants, Pizzerien und Bars siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de",
      shopping: "Für Informationen zu Geschäften und Märkten siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de",
      attractions: "Um zu entdecken, was in Rom zu besuchen ist, siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de",
      day_trips: "Für Informationen zu Tagesausflügen außerhalb Roms siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de",
      tickets: "Für Informationen zu Tickets für Museen, Veranstaltungen und Spiele siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=de"
    },
    es: {
      wifi: "Wi-Fi: El router está sobre la mesa. Gíralo para leer el SSID y la contraseña en la etiqueta. Si no funciona: comprueba que esté encendido, desenchúfalo 30 segundos y vuelve a conectarlo. Si continúa, escríbeme.",
      trash: "Basura: Antes de salir, cierra bien las bolsas y llévalas al punto de reciclaje frente a Piazza delle Cinque Scole (lado Lungotevere). El reciclaje es obligatorio: sigue las indicaciones y no dejes basura en la escalera ni fuera de la puerta.",
      heating: "Calefacción: El apartamento tiene una estufa eléctrica. Úsala solo cuando estés dentro y apágala siempre al salir por seguridad.",
      electric_panel: "Cuadro eléctrico: Si no hay luz, el cuadro está a la derecha antes de la puerta de salida. Todos los interruptores (incluido el pequeño blanco) deben estar arriba. Si continúa, fuera del edificio a la izquierda abre el contador y sube el interruptor.",
      check_in: "Check-in desde las 15:00. Acceso con Virtual Key: el enlace abre el portal y la puerta del apartamento. Dentro encontrarás las llaves sobre la mesa; después la Virtual Key se desactiva. Ayuda: +39 335 5245756.",
      check_out: "Check-out: Antes de salir apaga luces y calefacción, cierra las ventanas, deja las llaves sobre la mesa y cierra la puerta manualmente comprobando que quede bien cerrada.",
      city_tax_info: "Tasa turística: Obligatoria en Roma para no residentes. Para este apartamento es de 5 € por persona y noche, máximo 10 noches. Se cobra en nombre del Ayuntamiento de Roma.",
      laundry: "Lavandería: Si necesitas lavar ropa o toallas, escríbeme y te indicaré la mejor opción cercana.",
      building: "Edificio: Acceso mediante puerta con Virtual Key. Ubicado en la zona del Ghetto/Portico d'Ottavia, céntrica y parcialmente peatonal.",
      emergency: "Emergencias: UE 112 • Policía 113 • Ambulancia 118 • Bomberos 115",
      air_conditioning: "Aire acondicionado: Usa el mando. Pulsa MODE hasta que aparezca el símbolo del copo de nieve, ajusta a 24 °C y potencia auto. Apágalo siempre al salir.",
      parking: "Aparcamiento: El apartamento está en el centro histórico (ZTL - Zona de Tráfico Limitado). El acceso en coche está permitido solo de lunes a sábado de 19:00 a 7:30. Para encontrar el aparcamiento más cercano, busca la dirección del apartamento en Google Maps. Si tienes dificultades, llámame: +39 335 5245756.",
      services: "Para información sobre farmacias, hospitales, cajeros y otros servicios, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es",
      transport: "Para información sobre transporte, metro, autobuses y aeropuertos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es",
      restaurants: "Para recomendaciones de restaurantes, pizzerías y bares, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es",
      shopping: "Para información sobre tiendas y mercados, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es",
      attractions: "Para descubrir qué visitar en Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es",
      day_trips: "Para información sobre excursiones de un día fuera de Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es",
      tickets: "Para información sobre entradas para museos, eventos y partidos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/portico/?lang=es"
    }
  },

  trastevere: {
    it: {
      wifi: "Wi-Fi: Il router è sul mobile all'ingresso. Giralo per leggere sull'etichetta il nome della rete (SSID) e la password. Se non funziona: controlla che sia acceso, scollegalo 30 secondi e ricollegalo. Se il problema continua, scrivimi.",
      trash: "Spazzatura: In questo stabile NON si fa raccolta differenziata. Prima del check-out porta i rifiuti nei contenitori appena fuori dall'edificio, sul lato destro.",
      heating: "Riscaldamento: Per accenderlo vai nel corridoio subito dopo la cucina. Sulla parete di destra trovi il termostato: metti l'interruttore su ON e imposta 26 °C. In pochi minuti i termosifoni inizieranno a scaldarsi.",
      electric_panel: "Quadro elettrico: Se manca la corrente, il quadro è nell'antibagno, subito a destra entrando in casa. Controlla che tutti gli interruttori siano verso l'alto. Se non torna, scendi al piano -1: davanti alla porta del New York Institute apri lo sportello elettrico, cerca 'Bondi int. 9' e rialza l'interruttore sceso.",
      check_in: "Check-in dalle 15:00.",
      check_out: "Check-out: Prima di uscire spegni luci e aria condizionata, chiudi le finestre, lascia le chiavi sul tavolo e chiudi la porta manualmente verificando che sia ben chiusa.",
      city_tax_info: "Tassa di soggiorno: A Roma è prevista per gli ospiti non residenti. Per questo appartamento è di 5 € a persona per notte, fino a un massimo di 10 notti. La riscuotiamo per conto del Comune di Roma.",
      laundry: "Lavanderia: Se devi lavare vestiti o asciugamani, scrivimi e ti indico la soluzione migliore in zona in base ai tuoi orari.",
      building: "Edificio: Appartamento su Viale Trastevere, zona centrale e ben collegata. Accesso diretto dal portone su strada principale.",
      emergency: "Emergenze: UE 112 • Polizia 113 • Ambulanza 118 • Vigili del Fuoco 115",
      air_conditioning: "Aria condizionata: Usa il telecomando. Premi MODE finché appare il simbolo del fiocco di neve, imposta 24 °C e potenza auto. Spegni sempre quando esci.",
      parking: "Parcheggio: Vicino all'appartamento ci sono diversi parcheggi pubblici non custoditi (non lasciare oggetti visibili in auto) e parcheggi privati a pagamento. Puoi anche usare i parcheggi comunali con strisce blu.",
      services: "Per informazioni su farmacie, ospedali, bancomat e altri servizi consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it",
      transport: "Per informazioni su trasporti, metro, bus e aeroporti consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it",
      restaurants: "Per consigli su ristoranti, pizzerie e locali consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it",
      shopping: "Per informazioni su negozi e mercati consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it",
      attractions: "Per scoprire cosa visitare a Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it",
      day_trips: "Per informazioni su gite ed escursioni fuori Roma consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it",
      tickets: "Per informazioni su biglietti per musei, eventi e partite consulta la tua guida interattiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=it"
    },
    en: {
      wifi: "Wi-Fi: The router is on the cabinet near the entrance. Turn it to read the SSID and password on the label. If it doesn't work: check it's on, unplug it for 30 seconds and plug it back in. If the issue continues, message me.",
      trash: "Trash: There is NO recycling in this building. Before check-out, take the trash to the bins just outside the building, on the right side.",
      heating: "Heating: To turn it on, go to the hallway just after the kitchen. On the right wall you'll find the thermostat: switch it to ON and set 26 °C. The radiators will start warming up in a few minutes.",
      electric_panel: "Electric panel: If there's no power, the panel is in the bathroom anteroom, immediately on the right when entering. Make sure all breakers are up. If power doesn't return, go to floor -1: in front of the New York Institute door open the electrical box, look for 'Bondi int. 9' and reset the lowered switch.",
      check_in: "Check-in from 3:00 PM.",
      check_out: "Check-out: Before leaving, turn off lights and air conditioning, close the windows, leave the keys on the table and close the door manually, making sure it's properly locked.",
      city_tax_info: "City tax: Required in Rome for non-residents. For this apartment it is €5 per person per night, up to a maximum of 10 nights. Collected on behalf of the City of Rome.",
      laundry: "Laundry: If you need to wash clothes or towels, message me and I'll suggest the best nearby option based on your schedule.",
      building: "Building: Apartment on Viale Trastevere, central and well connected. Direct access from the main street entrance.",
      emergency: "Emergencies: EU 112 • Police 113 • Ambulance 118 • Fire Brigade 115",
      air_conditioning: "Air conditioning: Use the remote control. Press MODE until the snowflake symbol appears, set 24 °C and auto power. Always turn it off when leaving.",
      parking: "Parking: Near the apartment there are several unattended public parking lots (do not leave visible items in your car) and paid private parking facilities. You can also use municipal parking with blue lines.",
      services: "For information on pharmacies, hospitals, ATMs and other services, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en",
      transport: "For information on transport, metro, buses and airports, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en",
      restaurants: "For restaurant, pizzeria and bar recommendations, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en",
      shopping: "For information on shops and markets, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en",
      attractions: "To discover what to visit in Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en",
      day_trips: "For information on day trips and excursions outside Rome, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en",
      tickets: "For information on tickets for museums, events and matches, check your interactive guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=en"
    },
    fr: {
      wifi: "Wi-Fi : Le routeur est sur le meuble près de l'entrée. Tournez-le pour lire le SSID et le mot de passe sur l'étiquette. En cas de problème, vérifiez qu'il est allumé, débranchez-le 30 secondes puis rebranchez-le.",
      trash: "Déchets : Il n'y a PAS de tri sélectif dans cet immeuble. Avant le départ, déposez les sacs dans les conteneurs juste à l'extérieur du bâtiment, sur la droite.",
      heating: "Chauffage : Pour l'allumer, allez dans le couloir après la cuisine. Sur le mur de droite se trouve le thermostat : mettez-le sur ON et réglez à 26 °C. Les radiateurs chaufferont en quelques minutes.",
      electric_panel: "Tableau électrique : En cas de coupure, le tableau est dans l'antichambre de la salle de bain, immédiatement à droite en entrant. Vérifiez que tous les interrupteurs sont levés. Sinon, descendez à l'étage -1 : devant la porte du New York Institute, ouvrez le coffret, cherchez 'Bondi int. 9' et réarmez l'interrupteur.",
      check_in: "Arrivée à partir de 15h00.",
      check_out: "Départ : Avant de partir, éteignez lumières et climatisation, fermez les fenêtres, laissez les clés sur la table et fermez la porte manuellement.",
      city_tax_info: "Taxe de séjour : Obligatoire à Rome pour les non-résidents. Pour cet appartement : 5 € par personne et par nuit, maximum 10 nuits. Perçue pour la Ville de Rome.",
      laundry: "Blanchisserie : Si vous devez laver des vêtements ou serviettes, écrivez-moi et je vous indiquerai la meilleure solution à proximité.",
      building: "Immeuble : Appartement situé sur Viale Trastevere, quartier central et très bien desservi.",
      emergency: "Urgences : UE 112 • Police 113 • Ambulance 118 • Pompiers 115",
      air_conditioning: "Climatisation : Utilisez la télécommande. Appuyez sur MODE jusqu'au symbole flocon, réglez à 24 °C et puissance auto. Éteignez toujours en sortant.",
      parking: "Parking : Près de l'appartement, il y a plusieurs parkings publics non surveillés (ne laissez rien de visible dans la voiture) et des parkings privés payants. Vous pouvez également utiliser les parkings municipaux avec lignes bleues.",
      services: "Pour les informations sur pharmacies, hôpitaux, distributeurs et autres services, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr",
      transport: "Pour les informations sur transports, métro, bus et aéroports, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr",
      restaurants: "Pour les recommandations de restaurants, pizzerias et bars, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr",
      shopping: "Pour les informations sur magasins et marchés, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr",
      attractions: "Pour découvrir quoi visiter à Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr",
      day_trips: "Pour les informations sur excursions d'une journée hors de Rome, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr",
      tickets: "Pour les informations sur billets pour musées, événements et matchs, consultez votre guide interactif : https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=fr"
    },
    de: {
      wifi: "WLAN: Der Router steht auf dem Möbelstück im Eingangsbereich. Drehen Sie ihn, um SSID und Passwort auf dem Aufkleber zu lesen. Bei Problemen: 30 Sekunden vom Strom trennen und wieder anschließen.",
      trash: "Müll: In diesem Gebäude gibt es KEINE Mülltrennung. Vor dem Check-out den Müll in die Tonnen direkt rechts vor dem Gebäude bringen.",
      heating: "Heizung: Zum Einschalten in den Flur nach der Küche gehen. An der rechten Wand befindet sich der Thermostat: auf ON stellen und 26 °C einstellen. Nach wenigen Minuten werden die Heizkörper warm.",
      electric_panel: "Sicherungskasten: Bei Stromausfall befindet sich der Kasten im Vorbad rechts beim Eintreten. Prüfen, ob alle Schalter oben sind. Falls nicht, in Etage -1 gehen, vor der Tür des New York Institute den Kasten öffnen, 'Bondi int. 9' suchen und den Schalter hochstellen.",
      check_in: "Check-in ab 15:00 Uhr.",
      check_out: "Check-out: Vor der Abreise Licht und Klimaanlage ausschalten, Fenster schließen, Schlüssel auf dem Tisch lassen und die Tür manuell schließen.",
      city_tax_info: "Touristensteuer: In Rom für Nicht-Einwohner verpflichtend. Für diese Wohnung 5 € pro Person und Nacht, maximal 10 Nächte. Wird für die Stadt Rom erhoben.",
      laundry: "Wäscherei: Wenn Sie Kleidung oder Handtücher waschen müssen, schreiben Sie mir – ich empfehle eine Lösung in der Nähe.",
      building: "Gebäude: Wohnung an der Viale Trastevere, zentrale Lage mit sehr guter Anbindung.",
      emergency: "Notfälle: EU 112 • Polizei 113 • Rettung 118 • Feuerwehr 115",
      air_conditioning: "Klimaanlage: Verwenden Sie die Fernbedienung. MODE drücken bis das Schneeflocken-Symbol erscheint, 24 °C und auto einstellen. Beim Verlassen immer ausschalten.",
      parking: "Parkplatz: In der Nähe der Wohnung gibt es mehrere unbewachte öffentliche Parkplätze (lassen Sie keine sichtbaren Gegenstände im Auto) und kostenpflichtige Privatparkplätze. Sie können auch die städtischen Parkplätze mit blauen Linien nutzen.",
      services: "Für Informationen zu Apotheken, Krankenhäusern, Geldautomaten und anderen Services siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de",
      transport: "Für Informationen zu Transport, Metro, Bussen und Flughäfen siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de",
      restaurants: "Für Empfehlungen zu Restaurants, Pizzerien und Bars siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de",
      shopping: "Für Informationen zu Geschäften und Märkten siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de",
      attractions: "Um zu entdecken, was in Rom zu besuchen ist, siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de",
      day_trips: "Für Informationen zu Tagesausflügen außerhalb Roms siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de",
      tickets: "Für Informationen zu Tickets für Museen, Veranstaltungen und Spiele siehe deinen interaktiven Guide: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=de"
    },
    es: {
      wifi: "Wi-Fi: El router está en el mueble cerca de la entrada. Gíralo para leer el SSID y la contraseña en la etiqueta. Si no funciona: comprueba que esté encendido, desenchúfalo 30 segundos y vuelve a conectarlo. Si continúa, escríbeme.",
      trash: "Basura: En este edificio NO hay reciclaje. Antes del check-out, lleva la basura a los contenedores justo fuera del edificio, en el lado derecho.",
      heating: "Calefacción: Para encenderla ve al pasillo después de la cocina. En la pared derecha encontrarás el termostato: ponlo en ON y ajusta a 26 °C. En pocos minutos los radiadores se calientan.",
      electric_panel: "Cuadro eléctrico: Si no hay luz, el cuadro está en el antebaño, a la derecha nada más entrar. Comprueba que todos los interruptores estén arriba. Si no vuelve, baja a la planta -1: frente a la puerta del New York Institute abre el cuadro, busca 'Bondi int. 9' y sube el interruptor.",
      check_in: "Check-in desde las 15:00.",
      check_out: "Check-out: Antes de salir apaga luces y aire acondicionado, cierra las ventanas, deja las llaves sobre la mesa y cierra la puerta manualmente comprobando que quede bien cerrada.",
      city_tax_info: "Tasa turística: Obligatoria en Roma para no residentes. Para este apartamento es de 5 € por persona y noche, máximo 10 noches. Se cobra en nombre del Ayuntamiento de Roma.",
      laundry: "Lavandería: Si necesitas lavar ropa o toallas, escríbeme y te indicaré la mejor opción cercana.",
      building: "Edificio: Apartamento en Viale Trastevere, zona céntrica y bien comunicada. Acceso directo desde la calle principal.",
      emergency: "Emergencias: UE 112 • Policía 113 • Ambulancia 118 • Bomberos 115",
      air_conditioning: "Aire acondicionado: Usa el mando. Pulsa MODE hasta que aparezca el símbolo del copo de nieve, ajusta a 24 °C y potencia auto. Apágalo siempre al salir.",
      parking: "Aparcamiento: Cerca del apartamento hay varios aparcamientos públicos no vigilados (no dejes objetos visibles en el coche) y aparcamientos privados de pago. También puedes usar los aparcamientos municipales con líneas azules.",
      services: "Para información sobre farmacias, hospitales, cajeros y otros servicios, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es",
      transport: "Para información sobre transporte, metro, autobuses y aeropuertos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es",
      restaurants: "Para recomendaciones de restaurantes, pizzerías y bares, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es",
      shopping: "Para información sobre tiendas y mercados, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es",
      attractions: "Para descubrir qué visitar en Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es",
      day_trips: "Para información sobre excursiones de un día fuera de Roma, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es",
      tickets: "Para información sobre entradas para museos, eventos y partidos, consulta tu guía interactiva: https://shelly-cloud-opener-1.onrender.com/guides/trastevere/?lang=es"
    }
  }
};
